module.exports = [
  { name: 'Laurel Carter', email: 'laurel@jam3.com'},
  { name: 'Brendan Neufeld', email: 'brendan@jam3.com'},
  { name: 'Mat Jankowski', email: 'mat@jam3.com'},
  { name: 'Britney Sirianni', email: 'britney.sirianni@jam3.com'},
  { name: 'Media Ridha', email: 'media@jam3.com'},
  { name: 'Matt dilallo', email: 'matt.dilallo@jam3.com'},
  { name: 'Vadim Namniak', email: 'vadim@jam3.com'},
  { name: 'Serene', email: 'serene@jam3.com'},
  { name: 'Pablo Vio', email: 'pablo@jam3.com'},
  { name: 'Benson Wong', email: 'benson@jam3.com'},
  { name: 'Milica Stefancic', email: 'milica@jam3.com'},
  { name: 'Tina Ong', email: 'tina.ong@jam3.com'},
  { name: 'Pedro Barosso', email: 'pedro.barroso@jam3.com'},
  { name: 'Adam Slayer', email: 'adams@jam3.com'},
  { name: 'Candy Lee', email: 'candy.lee@jam3.com'},
  { name: 'Aaron Morris', email: 'aaron@jam3.com'},
  { name: 'All', email: 'all@jam3.com'},
  { name: 'Iran Reyes', email: 'iran.reyes@jam3.com'},
  { name: 'Dirk Vanginkel', email: 'dirk.vanginkel@jam3.com'},
  { name: 'Ragu Sivanandha', email: 'ragu@jam3.com'},
  { name: 'Madison Hayhoe', email: 'madison.hayhoe@jam3.com'},
  { name: 'Mark McQuillan', email: 'mark@jam3.com'},
  { name: 'Erik Iglikov', email: 'erik.iglikov@jam3.com'},
  { name: 'Jam Toronto', email: 'jam3media@gmail.com'},
  { name: 'Melissa', email: 'melissa@jam3.com'},
  { name: 'Alina Kulesh', email: 'alina@jam3.com'},
  { name: 'Jonathan McKinnell', email: 'jonathan@jam3.com'},
  { name: 'Greg Benedetto', email: 'greg@jam3.com'},
  { name: 'Jeesie', email: 'jessie@jam3.com'},
  { name: 'Roger', email: 'roger@jam3.com'},
  { name: 'Sara knowles', email: 'sara.knowles@jam3.com'},
  { name: 'Michael Dobell', email: 'michael@jam3.com'},
  { name: 'Felipe Vega', email: 'felipe.vega@jam3.com'},
  { name: 'Greg Bolton', email: 'greg.bolton@jam3.com'},
  { name: 'Amanda Westerhout', email: 'amanda@jam3.com'},
  { name: 'Matt DesLauriers', email: 'mattd@jam3.com'},
  { name: 'Tomasz Dysinski', email: 'tom@jam3.com'},
  { name: 'Marcelo Rogriguez', email: 'marcelo.rodriguez@jam3.com'},
  { name: 'Booker Sim', email: 'booker.sim@jam3.com'},
  { name: 'Mauri Vio', email: 'mauri@jam3.com'},
  { name: 'Marco Donnici', email: 'marco.donnici@jam3.com'},
  { name: 'Jordan Cuddy', email: 'jordan.cuddy@jam3.com'},
  { name: 'Lorraine Lau', email: 'lorraine.lau@jam3.com'},
  { name: 'erin ray', email: 'erin.ray@jam3.com'},
  { name: 'Heather Phenix', email: 'heather@jam3.com'},
  { name: 'Miguel Moraleda', email: 'miguel@jam3.com'},
  { name: 'Nick Poisson', email: 'nick@jam3.com'},
  { name: 'Vanessa Radman', email: 'vanessa@jam3.com'}
];
